spring.application.name=AUTH-SERVICE

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_auth_db
spring.datasource.username=postgres
spring.datasource.password=Manikanta@340

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=https://reasonable-grace-production-7cfd.up.railway.app/eureka
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey