spring.application.name=AUTH-SERVICE

server.port=8084

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=https://reasonable-grace-production-7cfd.up.railway.app/eureka
jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey