spring.application.name=api-gateway

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}

spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/accounts/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthentication

spring.cloud.gateway.routes[1].id=customer-service
spring.cloud.gateway.routes[1].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/customers/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthentication

spring.cloud.gateway.routes[2].id=transaction-service
spring.cloud.gateway.routes[2].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/transactions/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthentication

spring.cloud.gateway.routes[3].id=auth-service
spring.cloud.gateway.routes[3].uri=https://auth-service-85dj.onrender.com
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

eureka.client.service-url.defaultZone=${EUREKA_URL}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always