spring.application.name=customer-service
server.port=8081

eureka.client.service-url.defaultZone=https://reasonable-grace-production-7cfd.up.railway.app/eureka
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_customer_db
spring.datasource.username=postgres
spring.datasource.password=Manikanta@340

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true